### ISSUE TITLE
Why was this moved to Robotics?

### ISSUE THREAD

**Issue by Kulgann** [Unity-Technologies/v-hacd-unity#4]
This package is very useful for all game development. Why is being labeled with the robotics packages ?

**Comment by at669** [comment]
Hi @Kulgann--this repository is going under some changes currently, and is subject to change. It was moved to better support the source code and git history, but it stayed under the Unity Robotics team. This package is primarily being used for robotics simulation in Unity--notably, in the [URDF-Importer](https://github.com/Unity-Technologies/URDF-Importer). 

If you're finding the package useful, please feel free to elaborate on your use case and what your ideal workflow using VHACD would be. Thanks!

**Comment by Kulgann** [comment]
Hey @at669
We are primarily using this package to generate collision shapes for almost all interactable objects in one of our VR games. Since the tried and tested approach of approximating the shape with basic colliders was not giving us the desired result. You can check the game out [here]( https://store.steampowered.com/app/1480650/A_Very_Bad_Christmas_Eve/).

The current workflow is fine, ideally this would part of the core import pipeline and we would have a "Generate convex collision shapes" checkbox in the import settings of the model.
Have a great day.
