### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by benoithudson** [Unity-Technologies/v-hacd-unity#8]
liblibvhacd.dylib is compiled for Intel only.

I'd contribute a PR but this package seems to use a fork of the original -- or at least the entry points aren't in the current master at https://github.com/kmammou/v-hacd.git

**Comment by at669** [comment]
@benoithudson Unfortunately, this package is not currently supporting Apple Silicon. You can continue to feel free to use your silicon-compiled library in a fork if it's working well for you. I'll close out this issue for now, but go ahead and open a new issue if you run into a new situation. Thanks!
